sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
  - docker-compose build
  - docker logout

script:
  - docker-compose run --rm -e EX_ES_HOST=elasticsearch13 -e EX_ES_HOST_PORT=9200 app-tests
  - docker-compose run --rm -e EX_ES_HOST=elasticsearch22 -e EX_ES_HOST_PORT=9200 app-tests
  - docker-compose run --rm -e EX_ES_HOST=elasticsearch71 -e EX_ES_HOST_PORT=9200 app-tests

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: M2BhoVMq+n3pQ8QBitPElaLDT63eMbYJ5oR0Ty0QdS0JBB8eq+Y2BD3aV/YpnW9ISjZc99DSDAJxChy3WlcgkNv+kz2SbCUjc4TnAHlHLQPe5EDaH0Jz+6629E4hgAreeJ3qGeqOf/0i3XXGNXroEavjiLJYFyhuXP1qweV+h6pkFbTKZbIhfpPjNJ6YKH5zTGXB+Yq8rrASnqYRp4fLAqqw2ApZ+fBIhXHb98d2BTFITVp/n70awm7mUFqV1RD6CcNuR/Z8OzXHiP52icWTRJQzvnUck+bdtfVuaM4vj+UEKNJKnF/Tub8vkO1COpKouHZNOePzjqWvgMmCKCI3k4v7ZnqQrMxF09j/otKK+yYOlnhGiR8M1lJfYdfF5IK9tdBlIu09RBrvDFBfl0LDuh+mJG2CPQ0c2BaN7oc9DOANvEIrdynwCtv2mamzAkYcptNM/8YgZcATFdyHMMqLqAPSyTVIHV8VjVx6rOzAZCl/DjnplLZb81akh+Qm8dDr0qOhgEXvSpVyVld84CyKNLV9rODVJeQ1k/e3sj/rsZByWL+0O1fi2SsWNWh3cz7DkHATK3rRYfiplh4QhuD6Y+LlZl/St+ZHdfpWOsDjlqNvXG40zwLxGFCKXX6VEh/N3VV9t2vzNDitXM7YnZ5MxU1vCI+N8+E/+b+ANTwQWsE=
